### ISSUE TITLE
When i'm launching...

### ISSUE THREAD

**Issue by HP888** [Mojang/LegacyLauncher#21]
when the client turns on it shows an error:
Exception in thread "main" java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:76)

**Comment by jamierocks** [comment]
Nowhere near enough information to go on here, and frankly I don't see the problem being with LaunchWrapper anyhow, but rather whatever is invoking it.

**Comment by peterix** [comment]
This can happen when you use multiple tweakers and they don't handle command line arguments correctly.
